# -*- coding: utf-8 -*-
"""Tugas1 SDA Responsi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/108wM5yCPI0xVOM0rp6Ur229dLoBB8o7f

#Tugas 1 Struktur data dan Algoritma

* Python Primer

1. buatlah sebuah kode program yang mengecek zodiak cina seseorang berdasarkan bulan atau
tahun kelahirannya
"""

tahun_lahir = eval(input("Masukan Tahun Kelahiranmu : "))
zodiak_cina = tahun_lahir % 12

if zodiak_cina == 0:
  print('Monkey / Monyet')
elif zodiak_cina == 1:
  print ('Rooster / Ayam')
elif zodiak_cina == 2 :
  print ('Dog / Anjing')
elif zodiak_cina == 3 :
  print ('Pig / Babi')
elif zodiak_cina == 4 :
  print ('Rat / Tikus')
elif zodiak_cina == 5 :
  print ('Ox / Kerbau')
elif zodiak_cina == 6 :
  print ('Tiger / Macan')
elif zodiak_cina == 7 :
  print ('Rabbit / Kelinci')
elif zodiak_cina == 8 :
  print ('Dragon / Naga')
elif zodiak_cina == 9 :
  print ('Snake / Ular')
elif zodiak_cina == 10 :
  print ('Horse / Kuda')
else :
  print ('Sheep /  Kambing')

"""2. buatlah sebuah penghitung detak jantung sederhana untuk menghitung target detak jantung
seseorang yang sedang melaksanakan program diet untuk membakar lemak
"""

umur = eval(input("Masukkan usiamu : "))
detak_maks = 206.9 - (0.67 * umur)
target = 0.65 * detak_maks 
print("Target detak jantung mu untuk program diet membakar lemak yakni", target, "detak per menit.")

"""3. buatlah sebuah program untuk mencari bilangan terbesar dan terkecil dalam sebuah list"""

list_nilai = [15,30,7,44,123,690,33,11,234,778,5]
nilai_min = min(list_nilai)
nilai_maks = max(list_nilai)
print('nilai terbesar pada list: ', nilai_maks)
print('nilai terkecil pada list: ', nilai_min)
